### ISSUE TITLE
aws authentication

### ISSUE THREAD

**Issue by callmehiphop** [callmehiphop/storage-browser#1]
So for my developing purposes, I've just been using my access key & secret. This would be an obvious no-no for security reasons. AWS does **not** support OAuth, they instead rolled their own authentication system.

As far as I can tell there are two different ways of authenticating without a key/secret which are via [WebIdentityCredentials](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/WebIdentityCredentials.html) and [CognitoIdentityCredentials](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CognitoIdentityCredentials.html), both of which allow you to use your google oauth `id_token`.

I haven't been very successful with either, but I suspect it's because I don't have the correct IAM configurations for my buckets.

**Comment by jgeewax** [comment]
I think its not unreasonable at all that users are given a configuration page for the storage plugin where they have to enter their ID and secret. those tokens would (ideally) be stored in local storage...

thoughts?

**Comment by callmehiphop** [comment]
Personally I'd prefer that route, only because that requires less IAM configurations and maybe just a new CORS rule. Using `localStorage` would be kind of a one-off since we switched to Firebase recently, but I don't see why it's not possible.

**Comment by jgeewax** [comment]
i dont mind using firebase either -- so long as we get the security rules correct and all that (to be figured out later)

**Comment by callmehiphop** [comment]
Ok, that's cool with me, I'll just move forward with the assumption that we're using id and secret.

**Comment by stephenplusplus** [comment]
This introduces a new concept of configuration detail I didn't think of; private data. They'll need to be marked as such so that they aren't exposed during the "export/import a dashboard" process.

But otherwise, storing any arbitrary data is fine, so this certainly qualifies.

**Comment by stephenplusplus** [comment]
But side note, if there's a way to auth an Amazon account with Google auth info that we already have, that would be awesome.

**Comment by jgeewax** [comment]
Yea - it'd be cool if that were doable. I havent heard of anyone
authenticating for AWS with anything except the access key id and secret
key...

I always figured there'd be some private data, but what I didn't think
about was the idea of "credentials" that could be used by more than one
plugin. Ie, all plugins for your AWS account would probably want to be able
to auth using that secret data... We'll eventually have to deal with the
idea that people won't want to copy/paste their access/secret keys into
each plugin each time they add a new one that uses AWS...

**Comment by stephenplusplus** [comment]
I like the "eventually" part of that idea :)

And re: auth, haven't heard of it either until @callmehiphop mentioned
there were two ways to do it (?) in the first post.

**Comment by callmehiphop** [comment]
> We'll eventually have to deal with the
idea that people won't want to copy/paste their access/secret keys into
each plugin each time they add a new one that uses AWS...

I think that's actually easily solvable, we could just make an AWS plugin and on the plugin view it would essentially just be key/secret inputs.

After which any plugin that uses AWS could attempt to get creds from there like..

```javascript
try {
  var creds = $injector.get('AWSCreds');
} catch (e) {
  // fall back to plugin configuration
  var creds = {
    key: $plugin.key,
    secret: $plugin.secret
  };
}
```

**Comment by callmehiphop** [comment]
> And re: auth, haven't heard of it either until @callmehiphop mentioned there were two ways to do it (?) in the first post.

I wasn't very successful with these and they seem to require more setup that can really only be done via AWS console (which defeats the purpose)

**Comment by callmehiphop** [comment]
Closing this since we've decided to just store the secret & access key.
